### ISSUE TITLE
Mod.OnRemoved()

### ISSUE THREAD

**Issue by thale5** [Knighth/TreeUnlimiter#3]
I believe Mod.OnRemoved() should be OnDisabled(). That's what the modding API says and is invoked by PluginManager.

**Comment by Knighth** [comment]
Good point, can't believe I've never noticed that in there (all my others use OnDisabled). Will correct for next release.

**Comment by Knighth** [comment]
Addressed\correct in v1220 build04 now published.

**Comment by Knighth** [comment]
changes push out via steam. Closing.
